Fix fallout from changes to bootparam_utils.h
In the decompressor code, which is -fstandalone, changes to
bootparam_utils.h mean that memcpy() is called, but there is no
__memcpy() implementation at the time it is included. Ensure that this
header is included *after* string.h.

Fixes:

arch/x86/boot/compressed/misc.o: In function `decompress_kernel':
 misc.c:(.text+0x330e): undefined reference to `__memcpy'

Change-Id: I7fb6d45ad15f1657f630f2e236b12f7e218e0a37
Signed-off-by: Alistair Delva <adelva@google.com>